# Get the data from UCI ML Reprository through URL.

In [1]:
import urllib.request

In [2]:
f = urllib.request.urlretrieve("http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data.gz","kddcup.data.gz")

In [3]:
sc

In [4]:
raw_data= sc.textFile('kddcup.data.gz')

In [5]:
raw_data

kddcup.data.gz MapPartitionsRDD[1] at textFile at <unknown>:0

Parallelization With Spark RDDs

In [6]:
a= range(100)

In [7]:
a

range(0, 100)

In [8]:
list(a)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [9]:
list_rdd = sc.parallelize(a)

In [10]:
list_rdd

PythonRDD[3] at RDD at PythonRDD.scala:52

In [11]:
list_rdd.count()

100

In [12]:
list_rdd.take(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
# this Example illustrates how is the 
list_rdd.reduce(lambda a,b:a+b)

4950

RDD Operations Basics

In [14]:
#map function
rdd = sc.parallelize(['b','c','a'])
sorted(rdd.map(lambda x:(x,1)).collect())

[('a', 1), ('b', 1), ('c', 1)]

In [16]:
#filter
rdd = sc.parallelize(['a','b','c'])
rdd.filter(lambda x:x == 'a').collect()

['a']

In [17]:
#filter
rdd = sc.parallelize([1,10,34,45,9,13])
rdd.filter(lambda x:x%2 == 0).collect()

[10, 34]

In [25]:
rdd = sc.parallelize([1,3,4,10])
sorted(rdd.flatMap(lambda x: range(1,x)).collect())

[1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9]

In [27]:
rdd.flatMap(lambda x: [(x,x),(x,x)]).collect()

[(1, 1), (1, 1), (3, 3), (3, 3), (4, 4), (4, 4), (10, 10), (10, 10)]

In [29]:
rdd = sc.parallelizeoka(("a",[1,2]),("b",[4,5]),("c",[9,8]))
def f(x): return x
x.flatMapValues(f).collect()

TypeError: parallelize() takes from 2 to 3 positional arguments but 4 were given

In [31]:
m = sc.parallelize([(1,3),(4,5),(9,8)]).collectAsMap()
m[1]

3

Should be used when the residing array expected to be small
spark can collect and prallelize data on different machines
can be transparently operatable from one terminal
when collect is called, all the resulting RDD's will be loaded in the drivers memory.

In [33]:
contains_normal = raw_data.filter(lambda line:"normal." in line)
contains_normal.count()

972781

In [35]:
split_file = raw_data.map(lambda line:line.split(","))
split_file.take(5)

[['0',
  'tcp',
  'http',
  'SF',
  '215',
  '45076',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '1',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '1.00',
  '0.00',
  '0.00',
  '0',
  '0',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  'normal.'],
 ['0',
  'tcp',
  'http',
  'SF',
  '162',
  '4528',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '2',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '1.00',
  '0.00',
  '0.00',
  '1',
  '1',
  '1.00',
  '0.00',
  '1.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  'normal.'],
 ['0',
  'tcp',
  'http',
  'SF',
  '236',
  '1228',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '1',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '1.00',
  '0.00',
  '0.00',
  '2',
  '2',
  '1.00',
  '0.00',
  '0.50',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  'normal.'],
 ['0',
  'tcp',
  'http',
  'SF',
  '233',
  '2032',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '2',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '1.00',
  '0.00',
  '0.00',
  '3',
  '3',
  '1.00',
  '0.00',
  '0.33',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  'normal.'],
 ['0',
  'tcp',
  'http',
  'SF',
  '239',
  '486',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '3',
  '3',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '1.00',
  '0.00',
  '0.00',
  '4',
  '4',
  '1.00',
  '0.00',
  '0.25',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  '0.00',
  'normal.']]

Sampling/Filtering RDDs to pick out relevant Data points.

In [37]:
from time import time

In [44]:
sampled =  raw_data.sample(False,0.1,42)
contains_normal_sample = sampled.map(lambda line:line.split(",")).filter(lambda line:"normal" in line)

In [48]:
t0 = time()
mum_sampled = contains_normal_sample.count()
duration =time()- t0
mum_sampled

0

In [49]:
duration

36.39747953414917

In [51]:
contains_normal_sample = sampled.map(lambda line:line.split(",")).filter(lambda line:"normal" in line)
t0 = time()
mum_sampled = contains_normal_sample.count()
duration =time()- t0
duration

36.4029335975647

Take samples from the data : False, 1000 samples , random of 42.

In [54]:
data_in_memory = raw_data.takeSample(False,10,42)
contains_normal_py = [line.split(",") for line in data_in_memory if "normal" in line]

In [56]:
len(contains_normal_py)

1

Splitting DataSets and creating new combinations with set operations.

In [57]:
normal_sample = sampled.filter(lambda line: "normal." in line)

In [62]:
non_normal_sample = sampled.subtract(normal_sample)

In [60]:
sampled.count()

490705

In [64]:
normal_sample.count()

97404

In [65]:
non_normal_sample.count()

393301

In [67]:
# cartesian finding common values between2 distinct features.
feature1 = sampled.map(lambda line:line.split(",")).map(lambda features:features[1]).distinct()

In [79]:
feature2 = sampled.map(lambda line:line.split(",")).map(lambda features:features[2]).distinct()
feature0 = sampled.map(lambda line:line.split(",")).map(lambda features:features[0]).distinct()

In [80]:
f1 = feature1.collect()
f2 = feature2.collect()
f0 = feature0.collect()

In [70]:
len(feature1.cartesian(feature2).collect())

198

In [82]:
f0

['0',
 '1',
 '3',
 '58',
 '12',
 '2',
 '76',
 '43',
 '9',
 '71',
 '17',
 '4',
 '24',
 '27',
 '25',
 '20',
 '10',
 '30',
 '26',
 '21',
 '34',
 '36',
 '60',
 '9473',
 '12865',
 '10501',
 '22',
 '23',
 '32',
 '70',
 '64',
 '311',
 '80',
 '61',
 '192',
 '289',
 '44',
 '6',
 '5',
 '31',
 '18',
 '10007',
 '7',
 '19',
 '28',
 '8',
 '63',
 '142',
 '251',
 '107',
 '41',
 '354',
 '166',
 '118',
 '13',
 '29',
 '38',
 '139',
 '117',
 '53',
 '255',
 '298',
 '9769',
 '12249',
 '9675',
 '188',
 '91',
 '112',
 '50',
 '127',
 '57',
 '66',
 '78',
 '46',
 '82',
 '55',
 '189',
 '218',
 '418',
 '469',
 '15',
 '11',
 '475',
 '246',
 '456',
 '462',
 '147',
 '126',
 '110',
 '234',
 '260',
 '77',
 '3029',
 '3030',
 '67',
 '16',
 '42',
 '35',
 '19649',
 '48',
 '40',
 '331',
 '277',
 '146',
 '51',
 '1055',
 '3565',
 '256',
 '12096',
 '10514',
 '11958',
 '33',
 '420',
 '193',
 '176',
 '226',
 '103',
 '283',
 '69',
 '106',
 '140',
 '174',
 '54',
 '199',
 '297',
 '196',
 '99',
 '708',
 '268',
 '11921',
 '826',
 '14',
 '37',
 '310',
 '156',
 '11501',
 '4128',
 '13039',
 '589',
 '442',
 '460',
 '72',
 '79',
 '6284',
 '52',
 '10110',
 '10438',
 '198',
 '160',
 '137',
 '282',
 '22566',
 '45',
 '202',
 '11155',
 '338',
 '164',
 '429',
 '988',
 '3350',
 '18375',
 '17118',
 '707',
 '17551',
 '594',
 '12427',
 '739',
 '39',
 '179',
 '450',
 '86',
 '6867',
 '6718',
 '9494',
 '250',
 '206',
 '185',
 '59',
 '65',
 '74',
 '96',
 '90',
 '98',
 '17468',
 '9859',
 '563',
 '135',
 '85',
 '4468',
 '12077',
 '131',
 '73',
 '153',
 '248',
 '269',
 '133',
 '111',
 '624',
 '1295',
 '7782',
 '11867',
 '11291',
 '6432',
 '571',
 '328',
 '447',
 '227',
 '8742',
 '13164',
 '231',
 '186',
 '239',
 '116',
 '56',
 '97',
 '169',
 '49',
 '416',
 '10918',
 '19805',
 '347',
 '281',
 '88',
 '224',
 '408',
 '327',
 '95',
 '47',
 '89',
 '113',
 '181',
 '81',
 '62',
 '295',
 '12160',
 '567',
 '1174',
 '14085',
 '102',
 '93',
 '178',
 '530',
 '515',
 '1264',
 '8837',
 '94',
 '154',
 '278',
 '702',
 '572',
 '357',
 '10706',
 '14608',
 '10125',
 '10132',
 '10127',
 '5080',
 '210',
 '6521',
 '5066',
 '5044',
 '115',
 '214',
 '899',
 '645',
 '13578',
 '11754',
 '9943',
 '667',
 '441',
 '439',
 '543',
 '742',
 '13374',
 '769',
 '593',
 '893',
 '42529',
 '42384',
 '42068',
 '41909',
 '41761',
 '41496',
 '40511',
 '40100',
 '40025',
 '39890',
 '39602',
 '39527',
 '39313',
 '38635',
 '38531',
 '38294',
 '38065',
 '37688',
 '37478',
 '36700',
 '36674',
 '36653',
 '36633',
 '36530',
 '36204',
 '31998',
 '31971',
 '31769',
 '31749',
 '31401',
 '31381',
 '31280',
 '31194',
 '30955',
 '30558',
 '30197',
 '27740',
 '27341',
 '27201',
 '26983',
 '26367',
 '26231',
 '25990',
 '25950',
 '25481',
 '22721',
 '22681',
 '22436',
 '22396',
 '22376',
 '22316',
 '22216',
 '21987',
 '21907',
 '21887',
 '21866',
 '21787',
 '21747',
 '21430',
 '21354',
 '21243',
 '21163',
 '21143',
 '21023',
 '21003',
 '18704',
 '18478',
 '18238',
 '18118',
 '18058',
 '17459',
 '17419',
 '17005',
 '16713',
 '16533',
 '13878',
 '13758',
 '13698',
 '13658',
 '13638',
 '13448',
 '13388',
 '13328',
 '13201',
 '13113',
 '13013',
 '12953',
 '12893',
 '11941',
 '10999',
 '10123',
 '9615',
 '9595',
 '9455',
 '9375',
 '9355',
 '8815',
 '8217',
 '8197',
 '5658',
 '4921',
 '4741',
 '4440',
 '3941',
 '1091',
 '991',
 '831',
 '731',
 '590',
 '11540',
 '10159',
 '315',
 '4415',
 '10218',
 '7473',
 '9592',
 '748',
 '9108',
 '2428',
 '13096',
 '2547',
 '4268',
 '2477',
 '1991',
 '586',
 '3115',
 '345',
 '2964',
 '5718',
 '12618',
 '5782',
 '621',
 '1835',
 '5261',
 '1630',
 '2506',
 '2511',
 '9438',
 '17461',
 '1135',
 '2667',
 '5002',
 '2192',
 '2613',
 '1334',
 '4073',
 '7493',
 '2950',
 '4048',
 '9574',
 '15500',
 '4028',
 '2371',
 '17680',
 '898',
 '1070',
 '6164',
 '2022',
 '3751',
 '2910',
 '496',
 '1826',
 '757',
 '2323',
 '2423',
 '1284',
 '2213',
 '6513',
 '2012',
 '2897',
 '6674',
 '7116',
 '1015',
 '710',
 '1770',
 '1003',
 '13741',
 '8052',
 '440',
 '15629',
 '4912',
 '3664',
 '4992',
 '11074',
 '2236',
 '4581',
 '4560',
 '2032',
 '265',
 '2912',
 '810',
 '4695',
 '2829',
 '2563',
 '9460',
 '4238',
 '291',
 '608',
 '5631',
 '11364',
 '8888',
 '2398',
 '11242',
 '4091',
 '2558',
 '4830',
 '851',
 '10336',
 '1992',
 '2166',
 '2025',
 '842',
 '4401',
 '12604',
 '1627',
 '6715',
 '2781',
 '2762',
 '4831',
 '1373',
 '5123',
 '5132',
 '2431',
 '1594',
 '3087',
 '9322',
 '3116',
 '755',
 '3158',
 '1228',
 '30233',
 '10524',
 '5352',
 '1805',
 '1833',
 '5764',
 '5767',
 '627',
 '5332',
 '1788',
 '6014',
 '2089',
 '2084',
 '6029',
 '8018',
 '2108',
 '3890',
 '3924',
 '2133',
 '8549',
 '4250',
 '4246',
 '1780',
 '12128',
 '6075',
 '1785',
 '12132',
 '21379',
 '2461',
 '4296',
 '4298',
 '6763',
 '6764',
 '1824',
 '7873',
 '7876',
 '2159',
 '2470',
 '2468',
 '2469',
 '4940',
 '6052',
 '6056',
 '2460',
 '2465',
 '8026',
 '3578',
 '3582',
 '5561',
 '5557',
 '2130',
 '5552',
 '876',
 '3586',
 '8034',
 '5560',
 '10508',
 '5555',
 '15294',
 '12820',
 '8033',
 '3090',
 '3086',
 '1112',
 '1116',
 '4449',
 '4453',
 '4445',
 '9246',
 '9243',
 '6917',
 '4446',
 '4450',
 '1974',
 '9247',
 '2575',
 '9242',
 '11707',
 '1979',
 '4451',
 '12203',
 '2474',
 '2466',
 '12199',
 '7268',
 '7260',
 '2472',
 '2473',
 '7263',
 '7267',
 '7257',
 '2471',
 '4791',
 '4790',
 '4786',
 '4784',
 '2320',
 '2325',
 '4785',
 '2311',
 '4789',
 '12194',
 '9725',
 '4782',
 '2315',
 '4935',
 '7409',
 '7405',
 '4934',
 '4928',
 '9722',
 '9721',
 '7416',
 '7412',
 '7407',
 '1920',
 '7251',
 '7247',
 '2467',
 '2476',
 '7246',
 '4776',
 '4773',
 '4780',
 '2309',
 '7248',
 '7241',
 '4774',
 '4939',
 '320',
 '1731',
 '13195',
 '4951',
 '2898',
 '3334',
 '3434',
 '17132',
 '867',
 '8953',
 '1504',
 '1514',
 '3377',
 '9141',
 '936',
 '4903',
 '693',
 '900',
 '20252',
 '10827',
 '13501',
 '5942',
 '5925',
 '5879',
 '3891',
 '1172',
 '706',
 '3678',
 '5553',
 '4187',
 '1300',
 '2068',
 '2592',
 '5131',
 '809',
 '388',
 '847',
 '2298',
 '3246',
 '430',
 '1445',
 '592',
 '435',
 '9956',
 '9866',
 '1497',
 '10047',
 '18367',
 '3710',
 '855',
 '2515',
 '1845',
 '2538',
 '3821',
 '2980',
 '5798',
 '6984',
 '5840',
 '806',
 '8315',
 '5196',
 '8275',
 '6580',
 '173',
 '5473',
 '3153',
 '9406',
 '2106',
 '175',
 '9944',
 '3420',
 '1391',
 '2704',
 '3365',
 '8954',
 '2187',
 '3764',
 '6174',
 '2705',
 '6265',
 '2958',
 '400',
 '4426',
 '2819',
 '2960',
 '4535',
 '945',
 '2287',
 '3189',
 '4858',
 '1957',
 '275',
 '2105',
 '1261',
 '1037',
 '1444',
 '1340',
 '491',
 '1188',
 '1216',
 '920',
 '464',
 '544',
 '2889',
 '3145',
 '9590',
 '2071',
 '2376',
 '2646',
 '11555',
 '4832',
 '18303',
 '740',
 '171',
 '795',
 '7970',
 '10165',
 '1545',
 '3284',
 '5500',
 '15004',
 '5780',
 '3458',
 '359',
 '4164',
 '4473',
 '4509',
 '14615',
 '4115',
 '3489',
 '13120',
 '3634',
 '2410',
 '10681',
 '4351',
 '2009',
 '6981',
 '2955',
 '17105',
 '1240',
 '12383',
 '4809',
 '879',
 '2279',
 '3106',
 '2289',
 '1989',
 '2804',
 '2805',
 '975',
 '17104',
 '490',
 '1809',
 '20420',
 '12779',
 '370',
 '7550',
 '1100',
 '4060',
 '4165',
 '11144',
 '17779',
 '17784',
 '856',
 '10808',
 '10605',
 '5544',
 '2789',
 '2790',
 '3645',
 '7304',
 '24735',
 '894',
 '2976',
 '285',
 '4200',
 '109',
 '279',
 '2616',
 '11807',
 '12800',
 '8828',
 '13357',
 '11590',
 '18185',
 '3918',
 '2503',
 '1952',
 '3712',
 '2896',
 '3544',
 '2629',
 '940',
 '3358',
 '2270',
 '2448',
 '7930',
 '4630',
 '8919',
 '30073',
 '2739',
 '7154',
 '4658',
 '8153',
 '16370',
 '27938',
 '6214',
 '6230',
 '7805',
 '1095',
 '1589',
 '1573',
 '3690',
 '5482',
 '5465',
 '13007',
 '3744',
 '10683',
 '954',
 '10763',
 '7258',
 '6103',
 '26344',
 '758',
 '6744',
 '1382',
 '1327',
 '1319',
 '7430',
 '2389',
 '10665',
 '10653',
 '2157',
 '1522',
 '785',
 '26015',
 '8748',
 '9328',
 '7775',
 '6771',
 '747',
 '23963',
 '8580',
 '9916',
 '1786',
 '5214',
 '9917',
 '25445',
 '793',
 '3708',
 '11335',
 '4743',
 '293',
 '5937',
 '9383',
 '7148',
 '463',
 '1615',
 '2754',
 '6751',
 '3122',
 '2874',
 '2055',
 '23092',
 '2978',
 '2974',
 '939',
 '16579',
 '1832',
 '633',
 '9839',
 '1471',
 '6543',
 '12748',
 '9074',
 '8179',
 '434',
 '10812',
 '12868',
 '1388',
 '3759',
 '6901',
 '2332',
 '6615',
 '2064',
 '5712',
 '7989',
 '2811',
 '1603',
 '3325',
 '4539',
 '1035',
 '6645',
 '6837',
 '5905',
 '9461',
 '10486',
 '3540',
 '2344',
 '4299',
 '3352',
 '9631',
 '2427',
 '3905',
 '3553',
 '1224',
 '3105',
 '4286',
 '4474',
 '9234',
 '2036',
 '6623',
 '10640',
 '4279',
 '396',
 '3067',
 '2351',
 '5574',
 '16490',
 '17242',
 '17233',
 '15716',
 '324',
 '361',
 '9985',
 '3290',
 '5578',
 '4802',
 '6953',
 '5168',
 '7501',
 '1953',
 '6357',
 '5795',
 '3827',
 '6133',
 '846',
 '775',
 '14233',
 '1914',
 '1918',
 '713',
 '1064',
 '13654',
 '691',
 '3826',
 '13819',
 '1940',
 '7354',
 '12962',
 '3300',
 '2682',
 '3305',
 '3320',
 '12220',
 '12397',
 '4010',
 '3994',
 '2396',
 '12792',
 '4054',
 '12839',
 '12828',
 '2658',
 ...]

In [92]:
Sam1 = raw_data.map(lambda line:line.split(","))
Sam1.take(5)

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:51656)
Traceback (most recent call last):
  File "C:\Work\Hadoop\Spark\install\spark-2.3.3-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 929, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work\Hadoop\Spark\install\spark-2.3.3-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1067, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:51656)

In [94]:
f2

['http',
 'finger',
 'auth',
 'domain_u',
 'smtp',
 'ftp',
 'telnet',
 'eco_i',
 'ntp_u',
 'ecr_i',
 'other',
 'private',
 'pop_3',
 'ftp_data',
 'daytime',
 'remote_job',
 'supdup',
 'name',
 'ssh',
 'domain',
 'gopher',
 'time',
 'rje',
 'ctf',
 'mtp',
 'X11',
 'urp_i',
 'pm_dump',
 'IRC',
 'exec',
 'bgp',
 'nnsp',
 'iso_tsap',
 'http_443',
 'login',
 'shell',
 'printer',
 'efs',
 'courier',
 'uucp',
 'kshell',
 'klogin',
 'whois',
 'echo',
 'discard',
 'systat',
 'netstat',
 'hostnames',
 'csnet_ns',
 'pop_2',
 'sunrpc',
 'uucp_path',
 'nntp',
 'netbios_ns',
 'netbios_ssn',
 'netbios_dgm',
 'imap4',
 'sql_net',
 'vmnet',
 'link',
 'Z39_50',
 'ldap',
 'urh_i',
 'tftp_u',
 'red_i',
 'tim_i']

Learnt :
    Sampling/filtering to pick out relevant datapoints.
    How to split datasets and create new combinations with set operators.